"""The generated materialization project (§7).

Rendered files embed the COMPILATION identity only. `generated_project_hash` is
computed over these bytes and lives in GENERATED.lock — in this file it would be a
value the hash is taken over, which is the circularity §7's two phases remove.

GENERATED by featuregen.materialize.render — do not edit. Rendered for the package `sandbox_feature_cif_daily` by renderer version 1.
"""

__version__ = "1.0"

#: What the compilation chain decided, before a single file existed (§7).
COMPILATION_IDENTITY = {
    'formula_content_hashes': [
        'd107527da1c3f6ab7e6511344d183b12fe046018ee202c3a151e2e513721a5b0',
        'e53124ea18b2fc274434f799a1ee2802c2d169d4c53896629d8dabc652c63a86',
        '82fda384fe8b0121521226572e35171db903f3a81739bf7bf22a4824c0ca051f',
    ],
    'group_plan_hash': '11f9eae66a2d2837ebf8f45957076786032f592e7627dc8f2b0658959ec7d8ad',
    'ir_hashes': [
        '927aaa403ef961367ea6a5c069f7c8410d0cf10f8d4518ba4872a705ae786787',
        '57306f2b2fd8eb6a2660d54ab6e7f564f67242172a9da4d788db2e51a6cc0e3d',
        '985525a5f1410a2031049fbe3aa64866b83e3c2ab0f23c0a4f39bbf4db2889dc',
    ],
    'materialization_contract_hash': '2c9c4f8ab6236c0fcd6f04e21d81bf563178b4b829acb07a9c3673a874f2f803',
}
