"""The generated materialization project (§7).

Rendered files embed the COMPILATION identity only. `generated_project_hash` is
computed over these bytes and lives in GENERATED.lock — in this file it would be a
value the hash is taken over, which is the circularity §7's two phases remove.

GENERATED by featuregen.materialize.render — do not edit. Rendered for the package `sandbox_feature_cif_daily` by renderer version 3.
"""

__version__ = "1.0"

#: What the compilation chain decided, before a single file existed (§7).
COMPILATION_IDENTITY = {
    'formula_content_hashes': [
        '9a162dcf3f62d0c4fe0694542c9619393d033dd8560b4b690883ac69c9182c2b',
        'e53124ea18b2fc274434f799a1ee2802c2d169d4c53896629d8dabc652c63a86',
        '82fda384fe8b0121521226572e35171db903f3a81739bf7bf22a4824c0ca051f',
    ],
    'group_plan_hash': '4df4b1b83b20130e87522c66007f4dd084ac314e6ae18b9447a85be4c3ee62e2',
    'ir_hashes': [
        'a5b257ab3e2f42a21c4d007bb2f308d278b5a8f4fedfccb624eb89cc689cbd8a',
        '57306f2b2fd8eb6a2660d54ab6e7f564f67242172a9da4d788db2e51a6cc0e3d',
        '985525a5f1410a2031049fbe3aa64866b83e3c2ab0f23c0a4f39bbf4db2889dc',
    ],
    'materialization_contract_hash': '1f2ff12968846108c02ee11343b9a8e7ad8b37da4f5042fdf398c926aa8730d8',
}
