"""The two project hooks §7's launch story depends on.

GENERATED by featuregen.materialize.render — do not edit. Rendered for the package `sandbox_feature_cif_daily` by renderer version 1.
"""
from __future__ import annotations

from typing import Any

from kedro.framework.hooks import hook_impl
from pyspark import SparkConf
from pyspark.sql import SparkSession


class SparkSessionHook:
    """§7 — `kedro run` runs INSIDE a Spark session this hook configures.

    `spark-submit` only places the run on the cluster; it does not decide the session the
    pipeline computes in. Keeping the configuration here rather than in a submit command
    means the session is part of the artifact whose hash is recorded, instead of a set of
    flags typed on the day.
    """

    @hook_impl
    def after_context_created(self, context: Any) -> None:
        parameters = context.config_loader["spark"]
        configuration = SparkConf().setAll(sorted(parameters.items()))
        (
            SparkSession.builder.config(conf=configuration)
            .enableHiveSupport()
            .getOrCreate()
        )


class RunParametersHook:
    """§11.1 — execution reads EXACTLY the values run preparation resolved.

    Resolving and validating partitions is worthless if the pipeline then reads whatever it
    likes, so a run missing one of these refuses before a node executes. An UNEXPECTED
    parameter refuses for the same reason: it is a value somebody passed that nothing here
    planned to read, and silently ignoring it hides the disagreement.
    """

    REQUIRED_RUN_PARAMETERS = (
        'business_dt',
        'generation_id',
        'input_snapshots',
        'run_id',
        'sandbox_execution_hash',
        'staging_root',
    )
    GATE_CODE = 'RUN_PARAMETERS_MISSING'

    @hook_impl
    def before_pipeline_run(self, run_params: dict[str, Any], pipeline: Any,
                            catalog: Any) -> None:
        supplied = set((run_params or {}).get("runtime_params") or {})
        expected = set(self.REQUIRED_RUN_PARAMETERS)
        missing = sorted(expected - supplied)
        unexpected = sorted(supplied - expected)
        if missing or unexpected:
            raise RuntimeError(
                f"{self.GATE_CODE}: the run is missing {missing} and carries unexpected "
                f"{unexpected}. Run preparation resolves every one of "
                f"{sorted(expected)} and submission passes them; a run that reads anything "
                f"else is not the run that was prepared."
            )
