"""The project's pipelines.

GENERATED by featuregen.materialize.render — do not edit. Rendered for the package `sandbox_feature_cif_daily` by renderer version 2.
"""
from __future__ import annotations

from kedro.pipeline import Pipeline

from sandbox_feature_cif_daily.pipelines.materialize import create_pipeline


def register_pipelines() -> dict[str, Pipeline]:
    """Register the one pipeline this artifact contains.

    Registered EXPLICITLY rather than by discovery: a rendered artifact is identified by
    the hash of its bytes, so what it runs must be readable from those bytes and not from
    whatever happens to be importable at run time.
    """
    materialize = create_pipeline()
    return {"materialize": materialize, "__default__": materialize}
