"""Kedro project settings for the generated materialization project.

GENERATED by featuregen.materialize.render — do not edit. Rendered for the package `sandbox_feature_cif_daily` by renderer version 1.
"""

from sandbox_feature_cif_daily.hooks import RunParametersHook, SparkSessionHook

#: Both hooks are required, and both are §7's launch story rather than decoration:
#: `SparkSessionHook` is the Spark session `kedro run` runs inside, and
#: `RunParametersHook` is §11.1's refusal to run on parameters nobody prepared.
#: Kedro executes hooks last-in-first-out, so the parameter check runs BEFORE the session
#: is used and a refused run never touches the cluster.
HOOKS = (SparkSessionHook(), RunParametersHook())

CONFIG_LOADER_ARGS = {
    "base_env": "base",
    # The generated project ships exactly one configuration environment. Pointing the run
    # environment at a `local` that does not exist would leave conf/base/spark.yml
    # silently unmerged.
    "default_run_env": "base",
    "config_patterns": {"spark": ["spark*", "spark*/**"]},
}
