"""The `materialize` pipeline.

GENERATED by featuregen.materialize.render — do not edit. Rendered for the package `sandbox_feature_cif_daily` by renderer version 2.
"""
from __future__ import annotations

from sandbox_feature_cif_daily.pipelines.materialize.pipeline import create_pipeline

__all__ = ["create_pipeline"]
