"""The `materialize` pipeline's node functions.

Every storage location this pipeline touches is a CATALOG entry, so no path, table or
database name appears below: a location written here could not be reviewed with the rest
of the environment's configuration, and nothing reading the source could tell it apart
from a computed value.

GENERATED by featuregen.materialize.render — do not edit. Rendered for the package `sandbox_feature_cif_daily` by renderer version 2.
"""

from pyspark.sql import DataFrame


def build_spine(arg0):
    """Task 13/14 renders this body."""
    return None


def project_cross_border_value_ratio_90d_body_denominator(arg0, arg1):
    """Task 13/14 renders this body."""
    return None


def project_cross_border_value_ratio_90d_body_numerator(arg0, arg1):
    """Task 13/14 renders this body."""
    return None


def project_distinct_merchant_count_90d_body_expr(arg0, arg1):
    """Task 13/14 renders this body."""
    return None


def project_total_debit_amount_30d_body_expr(arg0, arg1):
    """Task 13/14 renders this body."""
    return None


def calculate_cross_border_value_ratio_90d(arg0, arg1, arg2):
    """Task 13/14 renders this body."""
    return None, None


def calculate_distinct_merchant_count_90d(arg0, arg1):
    """Task 13/14 renders this body."""
    return None, None


def calculate_total_debit_amount_30d(arg0, arg1):
    """Task 13/14 renders this body."""
    return None, None


def assemble(arg0, arg1, arg2, arg3, arg4, arg5, arg6):
    """Task 13/14 renders this body."""
    return None


def gate_and_publish(arg0):
    """Task 13/14 renders this body."""
    return None
