"""The `materialize` pipeline's wiring.

Every node states its inputs and outputs EXPLICITLY. Kedro would infer an
order either way; what an explicit wiring adds is that the order is
readable from the artifact instead of from the run that executed it.

GENERATED by featuregen.materialize.render — do not edit. Rendered for the package `sandbox_feature_cif_daily` by renderer version 2.
"""
from __future__ import annotations

from kedro.pipeline import Pipeline, node

from sandbox_feature_cif_daily.pipelines.materialize.nodes import (
    assemble,
    build_spine,
    calculate_cross_border_value_ratio_90d,
    calculate_distinct_merchant_count_90d,
    calculate_total_debit_amount_30d,
    gate_and_publish,
    project_cross_border_value_ratio_90d_body_denominator,
    project_cross_border_value_ratio_90d_body_numerator,
    project_distinct_merchant_count_90d_body_expr,
    project_total_debit_amount_30d_body_expr,
)


def create_pipeline(**kwargs) -> Pipeline:
    """The `materialize` pipeline: raw → intermediate → primary → staging → feature."""
    return Pipeline(
        [
            node(
                func=build_spine,
                inputs=['raw_banking__customers'],
                outputs='primary_spine',
                name='spine',
                tags=['primary'],
            ),
            node(
                func=project_cross_border_value_ratio_90d_body_denominator,
                inputs=['raw_banking__transactions', 'primary_spine'],
                outputs='intermediate_cross_border_value_ratio_90d__body_denominator',
                name='project_cross_border_value_ratio_90d_body_denominator',
                tags=['intermediate'],
            ),
            node(
                func=project_cross_border_value_ratio_90d_body_numerator,
                inputs=['raw_banking__transactions', 'primary_spine'],
                outputs='intermediate_cross_border_value_ratio_90d__body_numerator',
                name='project_cross_border_value_ratio_90d_body_numerator',
                tags=['intermediate'],
            ),
            node(
                func=project_distinct_merchant_count_90d_body_expr,
                inputs=['raw_banking__transactions', 'primary_spine'],
                outputs='intermediate_distinct_merchant_count_90d__body_expr',
                name='project_distinct_merchant_count_90d_body_expr',
                tags=['intermediate'],
            ),
            node(
                func=project_total_debit_amount_30d_body_expr,
                inputs=['raw_banking__transactions', 'primary_spine'],
                outputs='intermediate_total_debit_amount_30d__body_expr',
                name='project_total_debit_amount_30d_body_expr',
                tags=['intermediate'],
            ),
            node(
                func=calculate_cross_border_value_ratio_90d,
                inputs=['intermediate_cross_border_value_ratio_90d__body_denominator', 'intermediate_cross_border_value_ratio_90d__body_numerator', 'primary_spine'],
                outputs=['feature_staging_cross_border_value_ratio_90d', 'feature_manifest__cross_border_value_ratio_90d'],
                name='calculate_cross_border_value_ratio_90d',
                tags=['feature_staging'],
            ),
            node(
                func=calculate_distinct_merchant_count_90d,
                inputs=['intermediate_distinct_merchant_count_90d__body_expr', 'primary_spine'],
                outputs=['feature_staging_distinct_merchant_count_90d', 'feature_manifest__distinct_merchant_count_90d'],
                name='calculate_distinct_merchant_count_90d',
                tags=['feature_staging'],
            ),
            node(
                func=calculate_total_debit_amount_30d,
                inputs=['intermediate_total_debit_amount_30d__body_expr', 'primary_spine'],
                outputs=['feature_staging_total_debit_amount_30d', 'feature_manifest__total_debit_amount_30d'],
                name='calculate_total_debit_amount_30d',
                tags=['feature_staging'],
            ),
            node(
                func=assemble,
                inputs=['primary_spine', 'feature_staging_cross_border_value_ratio_90d', 'feature_staging_distinct_merchant_count_90d', 'feature_staging_total_debit_amount_30d', 'feature_manifest__cross_border_value_ratio_90d', 'feature_manifest__distinct_merchant_count_90d', 'feature_manifest__total_debit_amount_30d'],
                outputs='feature_group__assembled',
                name='assemble',
                tags=['feature_staging'],
            ),
            node(
                func=gate_and_publish,
                inputs=['feature_group__assembled'],
                outputs='feature_cif_daily',
                name='gate_and_publish',
                tags=['feature'],
            ),
        ]
    )
